### ISSUE TITLE
ucf24_project/labels？？？

### ISSUE THREAD

**Issue by panna19951227** [barloccia/MASK-CNN-for-actions-recognition-#2]
what ucf24_project/labels look like ?and what 'ucf24_project/rgb-images' looks like????

**Comment by adelmassimo** [comment]
Hi, unfortunately we have no more the dataset, but i think to remember that:

there are two folders, each containing other folders named as an activity (eg. "tennisSwing", "HorseRiding", ..).
Each activity folder contains other folders called like "g001_c02" that means sequence of frames 2 in video 1.
The structure described until here is equal for both 'ucf24_project/rgb-images' and ' ucf24_project/labels'.

- In each video folder, for labels, are presents as much as frames file called frame0xxx.txt in format
`12 x1 y1 x2 y2` where 12 is the index of the class observed in the bounding box defined from the other 4 values.

- In each video folder, for rgb-images, are present .png frames of target video.

**Comment by adelmassimo** [comment]
You should find the same version of the dataset the we've used here:
https://drive.google.com/file/d/1o2l6nYhd-0DDXGP-IPReBP4y1ffVmGSE/view
Good job!
